version: v0
tags: initial-config classes[]
drop-bands-wavelengths: # needs to be a list of tuples
  - [0, 440] # for one-band items
  - [1310, 1490]
  - [1770, 2050]
  - [2440, 2880]
datasets:
  soil:
    - /scratch/cmml/emit-frac/datasets/20260129_ym/soil_kmeans_subsampled_soil_soil.hdf5
    - /scratch/cmml/emit-frac/datasets/20260129_ym/soil_random_subsampled_rock_rock.hdf5
  pv:
    - /scratch/cmml/emit-frac/datasets/20260129_ym/pv_kmeans_subsampled_pv_pv.hdf5
  npv:
    - /scratch/cmml/emit-frac/datasets/20260129_ym/npv_kmeans_subsampled_npv_npv.hdf5
  snow+ice:
    - /scratch/cmml/emit-frac/datasets/20260129_ym/snow+ice_kmeans_subsampled_snow-ice_snow-ice.hdf5
  water:
    - /scratch/cmml/emit-frac/datasets/20260129_ym/water_kmeans_subsampled_water_water.hdf5
ood-test-set: /scratch/cmml/emit-frac/datasets/20260129_ym/validation.h5
simulation:
  n_components:
    soil: [1]
    pv: [1,2]
    npv: [1,2]
    snow+ice: [1,2]
    water: [1,2]
  n_classes_in_subsets: 3
  alpha: 0.3
  min_frac: 0.1
  alpha_uniform_low: 0.1
  alpha_uniform_high: 10.
  white_noise: 0.0001
  noise_scalar: 0.5
  noise_covariance_csv: /scratch/cmml/emit-frac/spectral_covariances_no_header_v2.csv
  return_fractions: true
  glint_upper_scalar: 0.15
  glint_lower_scalar: 0.0
subsample:
  test-fraction: 0.2
  selected-method:
  convex-hull:
    num_pc: 4
    n_samples: 100
    qhull_options:
  kmeans:
    num_pc: 4
    n_samples: 100
    init: k-means++
    n_init: auto
    max_iter: 300
    tol: 0.0001
    random_state: 2345
    algorithm: lloyd
  kmedoids:
    num_pc: 4
    n_samples: 10
    method: alternate
    init: k-medoids++
    max_iter: 300
    random_state: 2345
    metric: mahalanobis
  lhs:
    num_pc: 1
    hypercubes_per_dimension: 3
    samples_per_hypercube: 3
  random:
    n_samples: 10
dataloader:
  percent-static-data: 0.0
